export const container: string;
export const mainItem: string;
export const item: string;
export const modal: string;
export const hidebox: string;
export const box: string;
export const childBox: string;
export const itemImg: string;
export const itemName: string;
